[project]
name = "back-propagation"
version = "0.1.0"
description = "Studying back propagation"
readme = "README.org"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.20.3",
    "numpy>=2.1.3",
    "torch>=2.5.1",
]
