[project]
name = "gradients"
version = "0.1.0"
description = "Studying gradient descent"
readme = "README.org"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
]
